config/routes.rb
Rails.application.routes.draw do
  
  get "/events/calendar" => "events#calendar"
  resources :events
  resources :records
  resources :body_infos
  get 'calorie_calculator/index'

  resources :users
  resources :calorie_calculator
  root 'page#home'
  
  get '/welcome' => 'page#welcome'
  
  get '/about' => 'page#about'
  
  get 'signup' => 'users#signup'
  
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  
  delete "logout" => "users#logout", :as => "logout"
  
  get 'admin' => 'users#admin'
  
  get 'delete' => 'students#destroy'
  
  get 'Plan', to: 'plan#plan', as: 'plan'
  
  get 'Schedule', to: 'schedule#schedule', as: 'schedule'
     
  get 'Calorie Calculator', to: 'calorie_calculator#index', as: 'caloriecalculator'
  
  get 'Calorie Calculator Catch', to: 'calorie_calculator#catch', as: 'caloriecalculator_catch'
  
  post '/send_sms' => 'schedule#send_sms'
  
  get 'auth/facebook'
  get 'auth/facebook/callback', to: 'sessions#create'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true
  validates :description, presence: true
  validate :valid_dates

  def valid_dates
    if start_time >= end_time
      self.errors.add :end_time, ' has to be after start time'
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  # GET /events
  # GET /events.json
  def index
    @user = current_user
    @events = @user.events.all
  end
  
  def calendar
    @user = current_user
    @events = @user.events.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @user = current_user
    @event = @user.events.new(event_params)

    respond_to do |format|
      if @event.save
        if ((@event.start_time.to_time.to_i) - (Time.now.to_i) - 900) > 0
          ScheduleEmails.delay(run_at: ((@event.start_time.to_time.to_i) - (Time.now.to_i) - 900).seconds.from_now).send_email(@user, @event)
        end
        format.html { redirect_to events_url}
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url}
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title,  size: 50 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, cols: 50, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/calendar.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h1>Schedule Calendar</h1>
  
  <%= link_to 'New Event', new_event_path %>
  
  <script>
    $(document).ready(function() {
  
      // page is now ready, initialize the calendar...
  
      $('#calendar').fullCalendar({
          // put your options and callbacks here
          events: '/events.json'
      })
  
  });
  </script>
  
  <div id="calendar"></div>
  
</div>

app/views/events/edit.html.erb
<div class="container">
  <h1>Edit Event</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @event %> |
  <%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<div class="container">
  
  <h1>Schedule Events</h1>
  
  <table>
    <col width="100">
    <col width="250">
    <col width="200">
    <col width="200">
    <col width="40">
    <col width="60">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Start time</th>
        <th>End time</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @events.each do |event| %>
        <tr class="lineColor">
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.start_time %></td>
          <td><%= event.end_time %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>

  <%= button_to "New Event", new_event_path, :method => :get, class: "btn btn-default button" %>
  <button id="show_whatever" class="btn btn-default">Show Calendar</button>
</div>

<div class="container">
  <br>
  <div id="whatever">
    <div id="calendar"></div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#calendar').fullCalendar({
        // put your options and callbacks here
        events: '/events.json'
    })
  });
</script>

<script>
  $(function() {
    $("div#whatever").hide();
    $('button#show_whatever').click(function(event){
      event.preventDefault();
      $('div#whatever').toggle();
      $('#calendar').fullCalendar('refetchEvents');
    });
  });   
</script>

app/views/events/new.html.erb
<div class="container">
  <h1>New Event</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Title:</strong>
    <%= @event.title %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>
  
  <p>
    <strong>Start time:</strong>
    <%= @event.start_time %>
  </p>
  
  <p>
    <strong>End time:</strong>
    <%= @event.end_time %>
  </p>
  
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>
</div>