config/routes.rb
Rails.application.routes.draw do
  
  get "/events/calendar" => "events#calendar"
  resources :events
  resources :records
  resources :body_infos
  get 'calorie_calculator/index'

  resources :users
  resources :calorie_calculator
  root 'page#home'
  
  get '/welcome' => 'page#welcome'
  
  get '/about' => 'page#about'
  
  get 'signup' => 'users#signup'
  
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  
  delete "logout" => "users#logout", :as => "logout"
  
  get 'admin' => 'users#admin'
  
  get 'delete' => 'students#destroy'
  
  get 'Plan', to: 'plan#plan', as: 'plan'
  
  get 'Schedule', to: 'schedule#schedule', as: 'schedule'
     
  get 'Calorie Calculator', to: 'calorie_calculator#index', as: 'caloriecalculator'
  
  get 'Calorie Calculator Catch', to: 'calorie_calculator#catch', as: 'caloriecalculator_catch'
  
  post '/send_sms' => 'schedule#send_sms'
  
  get 'auth/facebook'
  get 'auth/facebook/callback', to: 'sessions#create'
  
end

app/models/body_info.rb
class BodyInfo < ActiveRecord::Base
    validates :gender, presence: true
    validates :age, presence: true
    validates :cm, presence: true, if: :no_feet_and_inches?
    validates :kg, presence:true, if: :no_pound?
    validates :pound, presence:true, if: :no_kg?
    validates :feet, presence:true, if: :no_cm_and_inches?

    
    def no_cm_and_inches?
        cm == nil && inches == nil
    end
    
    def no_feet_and_inches?
        feet == nil && inches == nil
    end
    
    def no_pound?
        pound == nil
    end
    
    def no_kg?
        kg == nil
    end
    
end

app/controllers/body_infos_controller.rb
class BodyInfosController < ApplicationController
  before_action :set_body_info, only: [:show, :edit, :update, :destroy]
   
 
  # GET /body_infos
  # GET /body_infos.json
  def index
    @body_infos = BodyInfo.all
  end

  # GET /body_infos/1
  # GET /body_infos/1.json
  def show
  end

  # GET /body_infos/new
  def new
    @body_info = BodyInfo.new
  end

  # GET /body_infos/1/edit
  def edit
  end

  # POST /body_infos
  # POST /body_infos.json
  def create
    @body_info = BodyInfo.new(body_info_params)

    respond_to do |format|
      if @body_info.save
        format.html { redirect_to @body_info, notice: 'Body info was successfully created.' }
        format.json { render :show, status: :created, location: @body_info }
      else
        format.html { render :new }
        format.json { render json: @body_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /body_infos/1
  # PATCH/PUT /body_infos/1.json
  def update
    respond_to do |format|
      if @body_info.update(body_info_params)
        format.html { redirect_to @body_info, notice: 'Body info was successfully updated.' }
        format.json { render :show, status: :ok, location: @body_info }
      else
        format.html { render :edit }
        format.json { render json: @body_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /body_infos/1
  # DELETE /body_infos/1.json
  def destroy
    @body_info.destroy
    respond_to do |format|
      format.html { redirect_to body_infos_url, notice: 'Body info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body_info
      @body_info = BodyInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def body_info_params
      params.require(:body_info).permit(:gender, :cm, :feet, :inches, :age, :kg, :pound, :username)
    end
    
   
end

app/helpers/body_infos_helper.rb
module BodyInfosHelper
end

app/views/body_infos/_form.html.erb
<%= form_for(@body_info) do |f| %>
  <% if @body_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body_info.errors.count, "error") %> prohibited this body_info from being saved:</h2>

      <ul>
      <% @body_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class = "field">
      <%= f.label :Username%> <br>
      <%= f.text_field :username, :value => current_user.name %>
  </div>




  <div class="field">
    <%= f.label :gender %><br>
    <%= f.radio_button:gender, 'Male'%> Male <br>
    <%= f.radio_button:gender, 'Female'%> Female <br>
  </div>
  
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
 
  <div class="field">
    <%= f.label :Height %><br>
    <%= f.number_field :cm %> cm or 
    <%= f.number_field :feet %> feet and 
    <%= f.number_field :inches %> inches
  </div>
 
  <div class="field">
    <%= f.label :Weight %><br>
    <%= f.number_field :kg %> kg or 
    <%= f.number_field :pound %> pound
  </div>

  <div class="actions">
      
      <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/body_infos/edit.html.erb
<div class="container">
  <h1>Edit your information</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', @body_info %> 
</div>

app/views/body_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Information</h1>

<!--<table>
  <thead>
    <tr>
      <th>Gender</th>
      <th>Cm</th>
      <th>Feet</th>
      <th>Inches</th>
      <th>Age</th>
      <th>Kg</th>
      <th>Pound</th>
      <th colspan="3"></th>
    </tr>
  </thead>-->

  <tbody>
    <% @body_infos.each do |body_info| %>
      <tr>
        <!--<td><%= body_info.gender %></td>-->
        <!--<td><%= body_info.cm %></td>-->
        <!--<td><%= body_info.feet %></td>-->
        <!--<td><%= body_info.inches %></td>-->
        <!--<td><%= body_info.age %></td>-->
        <!--<td><%= body_info.kg %></td>-->
        <!--<td><%= body_info.pound %></td>-->
        <td><%= link_to 'Show', body_info %></td>
        <td><%= link_to 'Edit', edit_body_info_path(body_info) %></td>
       <td><%= link_to 'Destroy', body_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Body info', new_body_info_path %>-->

app/views/body_infos/new.html.erb
<div class="container">
  <h1>Please enter the following information</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', caloriecalculator_path %>
</div>

app/views/body_infos/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Username:</strong>
    <%= @body_info.username %>
  </p>
  
  
  <p>
    <strong>Gender:</strong>
    <%= @body_info.gender %>
  </p>
  
  <p>
    <strong>Cm:</strong>
    <%= @body_info.cm %>
  </p>
  
  <p>
    <strong>Feet:</strong>
    <%= @body_info.feet %>
  </p>
  
  <p>
    <strong>Inches:</strong>
    <%= @body_info.inches %>
  </p>
  
  <p>
    <strong>Age:</strong>
    <%= @body_info.age %>
  </p>
  
  <p>
    <strong>Kg:</strong>
    <%= @body_info.kg %>
  </p>
  
  <p>
    <strong>Pound:</strong>
    <%= @body_info.pound %>
  </p>
  
  
  <%= link_to 'Edit', edit_body_info_path(@body_info) %> |
  <%= link_to 'Back', caloriecalculator_path %>
</div>