config/routes.rb
Rails.application.routes.draw do
  
  get "/events/calendar" => "events#calendar"
  resources :events
  resources :records
  resources :body_infos
  get 'calorie_calculator/index'

  resources :users
  resources :calorie_calculator
  root 'page#home'
  
  get '/welcome' => 'page#welcome'
  
  get '/about' => 'page#about'
  
  get 'signup' => 'users#signup'
  
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  
  delete "logout" => "users#logout", :as => "logout"
  
  get 'admin' => 'users#admin'
  
  get 'delete' => 'students#destroy'
  
  get 'Plan', to: 'plan#plan', as: 'plan'
  
  get 'Schedule', to: 'schedule#schedule', as: 'schedule'
     
  get 'Calorie Calculator', to: 'calorie_calculator#index', as: 'caloriecalculator'
  
  get 'Calorie Calculator Catch', to: 'calorie_calculator#catch', as: 'caloriecalculator_catch'
  
  post '/send_sms' => 'schedule#send_sms'
  
  get 'auth/facebook'
  get 'auth/facebook/callback', to: 'sessions#create'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Healthy life</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

<body class="<%= params[:controller] + '-' + params[:action] %>">
  <div class="navbar clearfix">
    <div class="container">

        <%= link_to "Healthy life", root_path, id:"title_style" %>

      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>

        <% if current_user %>
          <% if current_user.admin? %>
            <li><%= link_to "Users", admin_path %></li>
          <% end %>
          
          <li><%= link_to "Calorie Calculator",  caloriecalculator_path %></li>
          <li><%= link_to "Schedule", events_path %></li>
          <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= yield %>
  
</body>
</html>